export const AGENT_CONTEXT_PROFILES = Object.freeze({
  'setting-foundation': Object.freeze({ blocks: ['rules', 'selection', 'references'], maxChars: 18000 }),
  'setting-field': Object.freeze({ blocks: ['rules', 'selection', 'worldbook', 'references'], maxChars: 14000 }),
  'setting-section': Object.freeze({ blocks: ['rules', 'selection', 'worldbook', 'references'], maxChars: 22000 }),
  'source-import': Object.freeze({ blocks: ['rules', 'selection', 'references'], maxChars: 24000 }),
  'setting-places': Object.freeze({ blocks: ['rules', 'selection', 'worldbook', 'location', 'references'], maxChars: 22000 }),
  'setting-place': Object.freeze({ blocks: ['rules', 'selection', 'worldbook', 'location'], maxChars: 14000 }),
  'setting-research': Object.freeze({ blocks: ['rules', 'selection', 'worldbook', 'references'], maxChars: 20000 }),
  'setting-maintenance': Object.freeze({ blocks: ['rules', 'worldbook', 'history'], maxChars: 24000 }),
  'writing-selection': Object.freeze({ blocks: ['rules', 'style', 'selection', 'scene', 'memory', 'worldbook'], maxChars: 14000 }),
  'writing-cursor': Object.freeze({ blocks: ['rules', 'style', 'selection', 'scene'], maxChars: 12000 }),
  'writing-chapter': Object.freeze({ blocks: ['rules', 'style', 'selection', 'outline', 'worldbook'], maxChars: 24000 }),
  'narrative-scene': Object.freeze({ blocks: ['rules', 'style', 'scene', 'character', 'location', 'history', 'memory', 'worldbook'], maxChars: 32000 }),
  'narrative-advisor': Object.freeze({ blocks: ['rules', 'scene', 'character', 'worldbook'], maxChars: 16000 }),
  'scene-direction': Object.freeze({ blocks: ['rules', 'style', 'selection', 'scene', 'character', 'location', 'history', 'memory', 'outline', 'worldbook', 'references'], maxChars: 16000 }),
  'authoring-knowledge': Object.freeze({ blocks: ['rules', 'selection', 'scene', 'worldbook', 'outline', 'history', 'memory', 'references'], maxChars: 28000 }),
  'narrative-dialogue': Object.freeze({ blocks: ['rules', 'style', 'scene', 'character'], maxChars: 14000 }),
  'narrative-state': Object.freeze({ blocks: ['rules', 'scene', 'character', 'location', 'history', 'memory', 'worldbook'], maxChars: 20000 }),
  'narrative-memory': Object.freeze({ blocks: ['rules', 'scene', 'memory'], maxChars: 18000 }),
  'asset-summary': Object.freeze({ blocks: ['rules', 'selection', 'references'], maxChars: 12000 }),
  'observer-manuscript': Object.freeze({ blocks: ['rules', 'selection', 'memory', 'worldbook'], maxChars: 16000 }),
  'observer-quality': Object.freeze({ blocks: ['rules', 'selection', 'style'], maxChars: 10000 }),
  'materials-selection': Object.freeze({ blocks: ['rules', 'selection', 'references'], maxChars: 14000 }),
  'canvas-neighborhood': Object.freeze({ blocks: ['rules', 'selection', 'references'], maxChars: 14000 }),
  'storyboard-version': Object.freeze({ blocks: ['rules', 'selection', 'references'], maxChars: 12000 }),
  'storyboard-shot': Object.freeze({ blocks: ['rules', 'selection', 'references'], maxChars: 12000 })
})
